### ISSUE TITLE
Incompatible with python3

### ISSUE THREAD

**Issue by JoaquimEsteves** [calandoa/movescreen#11]
A print statement on line 30 makes it so the program is no longer
compatible with python3.

```bash
$ ./movescreen2.py left
  File "./movescreen2.py", line 30
    print arg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(arg)?
```

Patch is pretty simple

```diff
-     print arg
+     print(arg)
```

Although you should also probably delete this line. 
After deleting it it seems to work, tested on two screens

**Comment by calandoa** [comment]
Oups ! corrected...
