### ISSUE TITLE
Petition to add "maximize" option.

### ISSUE THREAD

**Issue by 4164696f73** [calandoa/movescreen#12]
I like it a ton, but it lacks maximization, in my opinion. Fill is useful for some applications/games, but maximization is better for all other cases.

Also, I realized the script just just uses pixels, would be better to change it to a percentage of the screen. So if you have a 1600x900 screen and 1920x1080, and you have something in the middle second screen and you pull it to the 1600x900 one, it now moves to 960x540 pixel position, and it'd be way nicer to have it in 800x450 position. Aka from 50% of 1920x1080 to 50% of 1600x900.

**Comment by calandoa** [comment]
I do not understand your first request. If the window is maximized, it will stay maximized after being moved to another screen.

For the second request, it looks like you need the `-r` option.

**Comment by 4164696f73** [comment]
The first question is to add a maximization option (basically fullscreen, as if you pressed the maximization button on your browser or file explorer), so that if you have a small window, instead of stretching it, you set it to fullscreen (basically pressing the maximization button on your browser/file explorer). Currently it only makes the window fit into the screen if it's bigger than the screen. Sorry if this is still confusing, lol.

Also, I completely missed the -r parameter for some reason, thanks! I also find it funny that it doesn't really work well with Y position when you have different monitor sizes (1920x1080 and 1600x900 in my case) - if you move the screen to your other screen and back, you can see how the Y position is lowering (window is going up the screen). Though it's not an issue for me because I'm also using a script that puts windows to the middle of the screen.

**Comment by calandoa** [comment]
The `fit` option does not maximize or toggle fullscreen, it just centers the windows. I do not understand if you are talking about maximize or fullscreen, but this should be handled by your window manager.  Which one are you using ?

**Comment by rpmohn** [comment]
I created pull request #13 that adds support for "max" and "unmax" because I also was looking for this functionality. Then I saw this issue asking for the same thing, so linking it here! I've got them mapped to Ctrl+Super+Up for "max" and Ctrl+Super+Down for "unmax".

**Comment by calandoa** [comment]
As I said, this should be managed by your window manager. Which one are you using?

**Comment by rpmohn** [comment]
Got it, yes I see I can remap it in XFCE using Settings > Window Manager > Keyboard. I withdraw my pull request, thank you!
