### ISSUE TITLE
Add option to move mouse pointer

### ISSUE THREAD

**Issue by wordlessly** [calandoa/movescreen#3]
I would love to be able to add a shortcut to only move the mouse to the "next" monitor. Something like:

movescreen.py next mouse

Sometimes the window is already on the correct screen, I just want to move the mouse there ;)

**Comment by calandoa** [comment]
Feature added.

**Comment by biographie** [comment]
Is it possible to move both the window and mouse simultaneously to another monitor?

**Comment by biographie** [comment]
When I chain the two commands in a terminal as such:
`/usr/local/bin/movescreen.py right | /usr/local/bin/movescreen.py right mouse
`
both the terminal and the mouse move to the window on the right. However, when I try using this as a keyboard shortcut in xfce, the mouse pointer changes from a cursor to a cross. Any ideas?

**Comment by JoaquimEsteves** [comment]
I'd also love moving the mouse along with the screen.

Something like:

```
movescreen right --include-mouse
```

Are PRs welcome on this repo?

**Comment by calandoa** [comment]
Ok, so I added the possibility to specify multiples id or mouse at the end, e.g. :
- "" -> active win
- "a" or "active" -> same
- "a m" -> active and mouse
- etc...
Can you please check if it suits your needs?

**Comment by JoaquimEsteves** [comment]
> Ok, so I added the possibility to specify multiples id or mouse at the end, e.g. :
> 
>     * "" -> active win
> 
>     * "a" or "active" -> same
> 
>     * "a m" -> active and mouse
> 
>     * etc...
>       Can you please check if it suits your needs?

That sounds __perfect__. I'm going to test it out ~~tomorrow~~ soon and report back :)

**Comment by JoaquimEsteves** [comment]
Sorry for the delay. I didn't have a second screen for a couple of weeks, which made it kind of hard to test 😂

The solution is lovely; although I opened a new issue regarding
the `print arg` on line 30.

**Comment by calandoa** [comment]
Ok thx for the feedback, closing
