### ISSUE TITLE
Problem moving windows when monitors only "touch" at one corner

### ISSUE THREAD

**Issue by wordlessly** [calandoa/movescreen#4]
![screenshot_2018-10-09_17-40-14](https://user-images.githubusercontent.com/37588166/46680983-8fca8480-cbea-11e8-9caf-2269bac37f42.png)
![screenshot_2018-10-09_17-39-48](https://user-images.githubusercontent.com/37588166/46680984-8fca8480-cbea-11e8-9553-0709ac302971.png)

In the pictures you see two monitor placements. For one moving windows works (when monitors are touching at one border).
The other monitor configuration (where monitors touch only at one corner) does not work for moving windows.

Why only touch at one corner? 

1. If monitors touch at one side instead of corner: the mouse cursor unintentionally moves to the second monitor. 
2. If monitors touch at one side instead of corner: snapping windows to one side of a monitor does not work since snapping will result in moving the window to the next monitor

I would prefer this setup (although I don't know if this is possible):
Monitors are fully isolated. 
There is no way to move the mouse pointer or a window manually to the second monitor. 
The only way to move the mouse pointer of  between monitors is using movescreen.py and a keyboard shortcut.

Is there a way to set it up like this?

**Comment by calandoa** [comment]
Next/prev arguments might help you on this case. Check other issue.
