### ISSUE TITLE
TypeError: list indices must be integers or slices, not float

### ISSUE THREAD

**Issue by squalou** [calandoa/movescreen#5]
Hi,

Thank you for this piece of code, works almost perfectly !
I'm back to xfce, finally :)

In my case (maybe due to python version in use : 3.7.1), I get the forementioned error at line 125.
A simple cast to int fixes it.

Here's the quick fix :

-- 	for xy in [[0], [1], [0,1]][dir_str.index(dir)/2]:

++ 	for xy in [[0], [1], [0,1]][int(dir_str.index(dir)/2)]:

could maybe even be better with an explicit call to 'floor' function but I didn't want to import 'math' for this,
I tested that casting to int does truncate anyway.

**Comment by calandoa** [comment]
I just tried with python3.6, the error is fixed but there is another problem: the window get maximized, I will check more in detail.

**Comment by calandoa** [comment]
This was a wrong observation, the fix has been commited and the script is now working with Python 3.6

**Comment by squalou** [comment]
great !
