### ISSUE TITLE
behaviour with 3 screens in 'inverted pyramidal' position

### ISSUE THREAD

**Issue by squalou** [calandoa/movescreen#6]
Hi,

This is not reaaly an issue, rather a 'weird situtation' due to my screen layout :

![screen-layout](https://user-images.githubusercontent.com/4623644/47987256-5b5dc180-e0df-11e8-9edd-bc8e93284591.png)

When on 'top row', using left right works perfectly.
But when asking to move down ... the movement moves the window below, which is expected, but does not 're' compute the position.
As a result, the window is 'cropped', I mean : it is not 'centered' on below screen. If it comes from the top-left screen, when it arrives at bottom screen the left part of the window is 'in the void'.

It works exactly as designed, that's why it's not reaaly an 'issue'.

I can use next / prev, works fine but is less 'natural'.

I'll probably tweak the program myself, and if I ever find something better I'll post a pull request.

Anyway thanks for the work !

**Comment by calandoa** [comment]
I added the keyword fit, check the readme. The options would be:

- press two shortcuts when moving the window down (one with 'down', one with 'fit')
- configure your window manager to call the script twice
- modify the script so several arguments can be specified and executed sequentially

**Comment by squalou** [comment]
I'll give this a try, indeed seems simple enough.
I hadn't played with 'fit' option yet, very interesting.

**Comment by squalou** [comment]
Works really great !
I even loop-call 'fit' option on all window when I disconnect my monitors, and all windows come back to good place.

**Comment by squalou** [comment]
Please note that I added a fix locally : 
```
# ... or get the new ones by applying offset on x (left/right), y (up/down), or both (next/prev)
--  for xy in [[0], [1], [0,1]][int(dir_str.index(dir)/2)]:
++  for xy in [[0,1], [0,1], [0,1]][int(dir_str.index(dir)/2)]:
```
This solves my situation entirely.

indeed : in my case when I move 'down' from top left, I also move right so I need to compute  both coordinates.
(same thing for other screens).

Maybe there are side effects, not for me so far

and finally is can be as simple as : 

```
++  for xy in [0,1]:
```

**Comment by calandoa** [comment]
Unfortunately I guess it would not work with 2x2 displays: a window in top-left would end up in bottom right after a "right" for instance.

**Comment by squalou** [comment]
not sure, worth a try.
from what I tried to understand, your algorithm tries to find which screen is "up", "down" etc. 
and uses screens coordiinates as offsets to move the window around.

In your case, when applying the "Y" offset it would add "zero" (because of the coordinates of the down screen), so arrive in the right place.

Can't try it myslef.
