### ISSUE TITLE
Suggest install of dependency 'wmctrl'

### ISSUE THREAD

**Issue by igormcoelho** [calandoa/movescreen#8]
First of all, thanks a lot for this script!
To make it work on Deepin, I had to install wmctrl package first.

`# apt install wmctrl`

According to some [random suggestion](https://unix.stackexchange.com/questions/434223/deepin-shortcut-to-move-window-to-other-monitor) on the internet, I have to remove a comma too on this line:
`id = re.search("window id # (0x[0-9a-f]+)", out).group(1)`

Finally, when no monitor is up, the "regular" error I get is:
```
python movescreen.py left
Traceback (most recent call last):
  File "movescreen.py", line 111, in <module>
    nscr = scr[r[dir][sidx]]
TypeError: list indices must be integers, not NoneType
```

Perhaps it's better to catch it.

**Comment by calandoa** [comment]
Corrected
